services:
  app:
    build:
      context: ..
      dockerfile: ./infra/app/Dockerfile
    container_name: paga_app
    ports:
      - "3000:3000"
  hardhat:
    build:
      context: ..
      dockerfile: ./infra/hardhat/Dockerfile
    container_name: paga_hardhat
    ports:
      - "8545:8545"