services:
  app:
    build:
      context: ..
      dockerfile: ./infra/app/Dockerfile
    container_name: paga_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: paga_mysql
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  hardhat:
    build:
      context: ..
      dockerfile: ./infra/hardhat/Dockerfile
    container_name: paga_hardhat
    ports:
      - "8545:8545"